### ISSUE TITLE
Logging out causes a server error: No user found online

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/road-to-legend-server#100]
## Debug Information

**In-Game Name**: Liquidor
**Operating System**: Win32 
**Browser/Version**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 

## Steps to Reproduce
1. Start the server
2. Log into the client
3. Log out

## Expected Behavior
Character being saved.

## Actual Behavior
Server error, but at least the server keeps running as the error has been caught, but the character may not have been saved.

Error is thrown at https://github.com/MrEliasen/path-to-power/blob/85e0d7a014c7675fa69fb71cece3921c1effa70f/server/game/components/character/manager.js#L394

Screenshot:
![](https://i.imgur.com/2FD8E3V.png)

Stack:
> Socket disconnected
> { user_id: '<redacted>',
>   display_name: 'Liquidor',
>   profile_image: 'https://static-cdn.jtvnw.net/jtv_user_pictures/d9812c5ad0621c85-profile_image-300x300.jpeg' }
> Unhandled rejection Error: No user found online, matching the user_id 5a87861d26fe753f90aec6dc
>     at CharacterManager._callee8$ (D:/Projekter/path-to-power/server/game/components/character/manager.js:394:19)
>     at tryCatch (D:\Projekter\path-to-power\server\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:65:40)
>     at Generator.invoke [as _invoke] (D:\Projekter\path-to-power\server\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:303:22)
>     at Generator.prototype.(anonymous function) [as next] (D:\Projekter\path-to-power\server\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:117:21)
>     at step (D:\Projekter\path-to-power\server\game\components\character\manager.js:44:202)
>     at D:\Projekter\path-to-power\server\game\components\character\manager.js:44:459
>     at CharacterManager.<anonymous> (D:\Projekter\path-to-power\server\game\components\character\manager.js:44:99)
>     at CharacterManager.save (D:\Projekter\path-to-power\server\game\components\character\manager.js:723:30)
>     at SocketManager.onDisconnect (D:/Projekter/path-to-power/server/game/components/socket/manager.js:154:44)
>     at Socket.<anonymous> (D:/Projekter/path-to-power/server/game/components/socket/manager.js:70:18)
>     at emitNone (events.js:105:13)
>     at Socket.emit (events.js:207:7)
>     at D:\Projekter\path-to-power\server\node_modules\socket.io\lib\socket.js:513:12
>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
>     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by DennisRas** [comment]
Apparently this doesn't happen when logging out.
This happens when following these steps:

1. Log into the game for the first time (delete your character if you already have one, having an account is fine though)
2. Do not select a city, but refresh the page.

This causes the error mentioned in the issue.
I'm not 100% sure what the issue is, since the source code references a "user", but I assume it has something to do with the character missing and the server trying to save it by id (it's not created in the manager or database before you select a city).
